/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"
#include "Rater.h"

std::string linux_system_tester::Greeter::greeting() {
    return std::string("Hello, World!");
}

int main () {
    Rater *rater = new SchedRater();
    std::string report = rater->evaluate();
    std::cout << report << std::endl;
    delete rater;
    return 0;
}
